fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

base:
    resource: "@BaseBundle/Controller/"
    type:     annotation
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: BaseBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]

page:
    path: /{url}
    defaults: { _controller: BaseBundle:Page:index }
    requirements:
        url: .*$
    methods: [GET]