forum:
    resource: "@ForumBundle/Controller/"
    type:     annotation
    prefix:   /

twig:
    resource: "@TwigBundle/Controller/"
    type:     annotation
    prefix:   /

cruise:
    resource: "@CruiseBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

base:
    resource: "@BaseBundle/Controller/"
    type:     annotation
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"

homepage:
    path: "/"
    defaults: { _controller: BaseBundle:Page:index }

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: BaseBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]

page:
    path: /{url}
    defaults: { _controller: BaseBundle:Page:page }
    requirements:
        url: .*$
